name: rybalko_dev
description: Portfolio website.

publish_to: 'none' 
version: 0.5.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.4.1
  material_design_icons_flutter: ^4.0.5345
  url_launcher: ^5.5.0
  url_launcher_web: ^0.1.2

dev_dependencies:
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/

        
    
    
