name: rybalko_dev
description: Portfolio website.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  typicons_flutter: ^0.3.1
  url_launcher: ^5.5.0
  url_launcher_web: ^0.1.2

flutter:
  uses-material-design: true

        
    
    
